### ISSUE TITLE
Error upgrading from NRF 4 to 5: next_dist_server_web_exports_next_response__WEBPACK_IMPORTED_MODULE_3__

### ISSUE THREAD

**Issue by SaadBazaz** [blomqma/next-rest-framework#127] opened 2024-02-14 14:40 UTC
I get a little trigger-happy when I see a new update.

Problem is, this time it broke my app and I can't understand why.

Here's the issue:
```
Next REST Framework encountered an error:
TypeError: next_dist_server_web_exports_next_response__WEBPACK_IMPORTED_MODULE_3__ is not a constructor
 ⨯ TypeError: next_dist_server_web_exports_next_response__WEBPACK_IMPORTED_MODULE_3__.json is not a function
    at handler (webpack-internal:///(rsc)/../../node_modules/.pnpm/next-rest-framework@5.1.0_next@14.0.4_zod@3.22.4/node_modules/next-rest-framework/dist/index.mjs:431:92)
    at /Users/saadbazaz/Projects/omni-tools/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:63257
    at /Users/saadbazaz/Projects/omni-tools/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/trace/tracer.js:133:36
    at NoopContextManager.with (/Users/saadbazaz/Projects/omni-tools/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/Users/saadbazaz/Projects/omni-tools/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
```

In a screenshot:
<img width="925" alt="Screenshot 2024-02-14 at 19 39 22" src="https://github.com/blomqma/next-rest-framework/assets/51885228/c2eed3ac-ce01-4c5a-a959-ba78bc124dfe">

Happens whenever I access /api

**Comment by blomqma** [comment] 2024-02-14 20:59
Yeah I just noticed the same issue, this is related to the changes of considering Next.js as a peer dependency when building the production bundle of the library, should've created an experimental release to test this first... Anyways, this is fixed in `v5.1.1`, so upgrading to that should work.

**Closed by blomqma** 2024-02-14 20:59 UTC

**Comment by blomqma** [comment] 2024-02-14 21:08
@SaadBazaz Looks like the attempted fix in `v5.1.1` did't resolve the issue, `v5.1.2` is now live that contains _actual_ fix.

**Comment by blomqma** [comment] 2024-02-14 21:32
> @SaadBazaz Looks like the attempted fix in `v5.1.1` did't resolve the issue, `v5.1.2` is now live that contains a _working_ fix.

And due to the same recent changes there was also another issue that might cause `next build` to fail depending on your environment, so upgrading to `v5.1.3` addresses that as well.

**Comment by SaadBazaz** [comment] 2024-02-15 03:01
/API works now! 

However, some routes aren't visible at all, even though their structure is similar to the others and they're not in ignored

**Comment by blomqma** [comment] 2024-02-15 22:15
> /API works now!
> 
> However, some routes aren't visible at all, even though their structure is similar to the others and they're not in ignored

For this issue I need more information. Generating the OpenAPI spec with the CLI, the documentation and calling the API endpoints seem to work fine in my environment with `v5.1.3`. Can you describe further about your problem about your API routes not being visible and how to reproduce it.
