### ISSUE TITLE
Nested routes do not appear in Openapi.json

### ISSUE THREAD

**Issue by momegas** [blomqma/next-rest-framework#82] opened 2023-10-17 12:39 UTC
<img width="412" alt="Screenshot 2023-10-17 at 3 37 19 PM" src="https://github.com/blomqma/next-rest-framework/assets/21096981/7bca576c-5df7-48c8-b354-1d2ee9d88f8e">

I have created a nested route (ex. `/app/api/test1/test2/route.ts`) and it does not work as expected. While the same with one less nested route works fine (ex `/app/api/test1/route.ts`)

**Comment by blomqma** [comment] 2023-10-17 22:47
Hey, can you answer these questions so I can provide better help for you, thanks:
* What version of Next REST Framework are you using?
* How is your route handler defined in that file?
* What does your docs endpoint `defineDocsRoute` configuration look like?

**Comment by momegas** [comment] 2023-10-19 11:13
- Latest NPM version
- Same as docs
- Same as docs

Sorry I cant give you actual code but I removed the package for now so I could moev forward

**Comment by blomqma** [comment] 2023-10-19 18:37
After testing with the file path you provided, I'm unable to reproduce this. I'll encourage you to try again with the latest version by following docs as the API has changed a bit, but I'm closing this issue for now.

**Closed by blomqma** 2023-10-19 18:37 UTC
