### ISSUE TITLE
openapi.json URL / proto mangled

### ISSUE THREAD

**Issue by drmarshall** [blomqma/next-rest-framework#70] opened 2023-10-06 01:04 UTC
Great project.

Recently, in production on a remote, https host (but not development or running with `NODE_ENV=production` locally), I am finding the URI for the GET for `openapi.json` to be mangled:

`NetworkError when attempting to fetch resource. https,http://example.com/api/public/openapi.json`

I see that, indeed, the page requests a filename is mangled:
```
scheme: https://
host: example.com
filename | /api/public/https,http:/example.com/api/public/openapi.json
```

...and there is a 308 redirect loop (presumably from the catchall router?).

I was previously on 0.8.0 and issue remains in 1.2.2. 

My setup:

```
export const { defineCatchAllApiRoute, defineApiRoute } = NextRestFramework({
  deniedPaths: ["/api/trpc/**", "/api/auth/**"],
  apiRoutesPath: "src/pages/api",
  swaggerUiPath: `/api/public`,
  exposeOpenApiSpec: true,
});
```

My definedApiRouters live in `src/pages/api/public/...`

I presume that the scheme changing from http (local) -> https (remote) is the cause, but looking at code, I cannot trace the error precisely.

Any insights appreciated but not expected as I cannot confirm this is a bug (versus a config error on my end).

**Comment by blomqma** [comment] 2023-10-09 20:23
Could you check what kind of values do the protocol request headers (`x-forwarded-proto`, `proto`) have in your production environment when you encounter this issue. I think this might occur when the request goes through multiple proxies or load balancers, each one adding their own protocol to the forwarded request. If this is the reason, it should be fairly simple to fix.

**Comment by blomqma** [comment] 2023-10-15 15:04
I've made some changes to the protocol parsing logic in `v2.0.1`. I also managed to reproduce the infinite request loop issue when using pages router and that should be fixed as well. Could you try if this issue still occurs for you with the latest version?

**Closed as completed** 2023-10-16 18:50 UTC
